'use client'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TradingCard from '@/components/card';
import { useRouter } from 'next/router'
import RotateCard from '@/components/rotate';
import NavButton from '@/components/navbutton';

import { Table, TableCell, TableRow } from '@mui/material';
import decks from '@/resources/cards';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();
  if(router.isReady==false)
  {
    return <></>
  }
  const splitPath = router.asPath.split('/')
  const set = splitPath[splitPath.length - 2]
  if (set==undefined || set==""){
    router.push('/')
  }
  const root = decks.filter(a=>a.title==set)[0].root
  const image = splitPath[splitPath.length - 1]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>


        <TradingCard image={image} set={set} root={root}/>
        <center>
          <Table>
            <TableRow>
              <TableCell>
              <NavButton direction="prev"/>
              </TableCell>
              <TableCell>
                <RotateCard />

              </TableCell>
              <TableCell>
              <NavButton direction="next"/>
              </TableCell>
            </TableRow>

          </Table>
        </center>
      </main>
    </>
  )
}
